# Docker Compose para desenvolvimento com portas customizáveis
version: '3.8'

services:
  # Banco de dados vetorial Weaviate
  weaviate:
    image: semitechnologies/weaviate:latest
    ports:
      - "${WEAVIATE_PORT:-8080}:8080"
      - "50051:50051"
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'false'
      AUTHENTICATION_APIKEY_ENABLED: 'true'
      AUTHENTICATION_APIKEY_ALLOWED_KEYS: '${WEAVIATE_API_KEY:-minha-chave-secreta-dev}'
      AUTHENTICATION_APIKEY_USERS: '${WEAVIATE_API_KEY:-minha-chave-secreta-dev}'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'none'
      ENABLE_MODULES: ''
      CLUSTER_HOSTNAME: 'node1'
    volumes:
      - weaviate_data:/var/lib/weaviate
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/v1/.well-known/ready"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Backend API (FastAPI)
  backend:
    build: 
      context: .
      dockerfile: ${DOCKERFILE:-Dockerfile}
    ports:
      - "${BACKEND_PORT:-8000}:8000"
    environment:
      - WEAVIATE_API_KEY=${WEAVIATE_API_KEY:-minha-chave-secreta-dev}
      - WEAVIATE_URL=http://weaviate:8080
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - TAVILY_API_KEY=${TAVILY_API_KEY}
    env_file:
      - .env
    volumes:
      - ./failed_responses.log:/app/failed_responses.log
      - ./logs:/app/logs
    depends_on:
      weaviate:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/docs"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  weaviate_data:
