apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: ethic-companion-backend
  annotations:
    run.googleapis.com/ingress: all
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: "100"
        run.googleapis.com/cpu-throttling: "false"
        run.googleapis.com/memory: "1Gi"
        run.googleapis.com/cpu: "1000m"
    spec:
      serviceAccountName: ethic-companion-backend@ethic-companion-v2.iam.gserviceaccount.com
      containerConcurrency: 80
      timeoutSeconds: 300
      containers:
      - image: gcr.io/ethic-companion-v2/ethic-companion-backend
        ports:
        - name: http1
          containerPort: 8000
        env:
        - name: PORT
          value: "8000"
        - name: ENVIRONMENT
          value: "production"
        - name: GOOGLE_CLOUD_PROJECT
          value: "ethic-companion-v2"
        resources:
          limits:
            cpu: 1000m
            memory: 1Gi
